/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Included_com_pisces_core_relation_Ioc */

#ifndef _Included_com_pisces_core_relation_Ioc
#define _Included_com_pisces_core_relation_Ioc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pisces_core_relation_Ioc
 * Method:    getRelationType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_pisces_core_relation_Ioc_getRelationType(
    JNIEnv* env, jclass cls, jclass beanCls, jint sign);

JNIEXPORT jint JNICALL Java_com_pisces_core_relation_Ioc_getRelationReverseSign(
    JNIEnv* env, jclass cls, jclass beanCls, jint sign);

JNIEXPORT jclass JNICALL Java_com_pisces_core_relation_Ioc_getEntityClass(
    JNIEnv* env, jclass cls, jclass beanCls, jint sign);

JNIEXPORT jclass JNICALL Java_com_pisces_core_relation_Ioc_getEntityClassByName(
    JNIEnv* env, jclass cls, jclass beanCls, jstring sign);

#ifdef __cplusplus
}
#endif
#endif
