/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Included_com_pisces_core_Initializer */

#ifndef _Included_com_pisces_core_Initializer
#define _Included_com_pisces_core_Initializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pisces_core_Initializer
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pisces_core_Initializer_load(JNIEnv* env,
                                                             jclass cls,
                                                             jobject clses);

#ifdef __cplusplus
}
#endif
#endif
