#ifndef APS_ENUMS_EInstruction_INCLUDE
#define APS_ENUMS_EInstruction_INCLUDE
#include "../../common/Export.h"

namespace aps {

DEFINE_ENUM(ResInsertRule, PLANLAST, PLANEARLIESTIDLE)
DEFINE_ENUM(ResSelectRule, PREVSET, POSTSET, WAITTIME, MANUFTIME, BALANCE,
            SAMEITEM, SAMEORDER, AROUNDWORK, POSTRES, SAMEASSISTANTRES,
            RESPRIORITY)
DEFINE_ENUM(WorkSortRule, ORDERDELIVERY, ORDERPRIORITY, ORDERESTSTART, ORDERQTY,
            ORDERRECEIVEDATE, ORDERLETMINUSEST, ORDERSURPLUS, REMAINROUTSTEPQTY,
            REMAINMANUFTM, MINSTEPREMAINTM, WORKLET, WORKEST, ORDERSTOCKRELA,
            ORDERFIRSTWORKSTART, HAVEHIGHWORK, WORKRESQTY, TOPORDERDELIVERY,
            TOPORDERPRIORITY, TOPORDERCODE)
DEFINE_ENUM(ItemTimeLimit, INVENTORY, PURCHASE, WORKORDER)
DEFINE_ENUM(WorkStatusLimit, CONFIRM, STARTPRODUCT, FINISH)
DEFINE_ENUM(DeleteOrderLimit, NO_DONE, NOPLAN, NO_DONE_SEND,
            NO_DONE_SEND_CONFIRM)

}  // namespace aps
#endif  // APS_ENUMS_EInstruction_INCLUDE