#ifndef APS_EMstr_INCLUDE
#define APS_EMstr_INCLUDE
#include "../../common/Export.h"
#include "MultiEnum.h"

namespace aps {
	
DEFINE_ENUM(ItemType, PRODUCT, HALF_PRODUCT, SRC_MATERIALS, PUR_PRODUCT,
            INTER_PRODUCT, VIRTUAL)
DEFINE_ENUM(SupplyWay, NOSUPPLY, BATCH, ONEBYONE)
DEFINE_ENUM(ItemPrepareWay, NO_PREPARE, SELF_SUPPLY, PURCHASE)
DEFINE_ENUM(ResType, PRACTICE, TOOL)
DEFINE_ENUM(ResCategory, LIMITLESS, SINGLE, MULTIPLE, BATCH)
DEFINE_ENUM(TimeRoundWay, NOROUND, UPWARD, DOWNWARD, ROUNDING)
DEFINE_ENUM(EffectSubTask, PREVSET, MANUF, POSTSET)
DEFINE_ENUM(ResLockWay, NOLOCK, MANUFSTART, MANUFEND)
DEFINE_MULTI_ENUM(EffectTaskType, PREVSET, MANUF, NEXTSET)

}  // namespace aps
#endif  // APS_EMstr_INCLUDE