#ifndef APS_ETech_INCLUDE
#define APS_ETech_INCLUDE
#include "../../common/Export.h"

namespace aps {

DEFINE_ENUM(SchDirection, OBVERSE, REVERSE)
DEFINE_ENUM(ResCombManufWay, PRACTICE, MAXTOOLRES, MINTOOLRES, AVGTOOLRES,
            MAXALLRES, MINALLRES, AVGALLRES)
DEFINE_ENUM(ResCombLockWay, KEEPORIGIN, PRACTICE, MAXALLRES)
DEFINE_ENUM(TailDealWay, NODEAL, CEILING, APPEND)
DEFINE_ENUM(UseType, PRACTICE, FIRSTTOOL, SECONDTOOL, THIRDTOOL, FOURTHTOOL,
            FIFTHTOOL, SIXTHTOOL)
DEFINE_ENUM(ContinuousType, ES, SS, EE, SSEE)

}  // namespace aps
#endif  // APS_ETech_INCLUDE